# Generated by Django 4.2.6 on 2023-10-19 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_finance'),
        ('customer', '0002_alter_customer_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('bill_no', models.IntegerField(blank=True, null=True, verbose_name='Bill No.')),
                ('purchase_date', models.DateField(verbose_name='Purchase date')),
                ('imei_no', models.CharField(blank=True, help_text='Enter the unique IMEI No.', max_length=50, null=True, verbose_name='IMEI No.')),
                ('qty', models.IntegerField(default=0, verbose_name='Quantity')),
                ('dp', models.FloatField(default=0, verbose_name='Down payment')),
                ('emi', models.FloatField(default=0, verbose_name='EMI per month')),
                ('total_month', models.IntegerField(default=0, verbose_name='Total months to pay EMI')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sold by')),
                ('customer', models.ForeignKey(help_text='Choose one customer', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.finance')),
                ('product', models.ForeignKey(blank=True, help_text='Choose your desired product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
