# Generated by Django 4.2.6 on 2023-10-26 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_producttype_alter_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Invoice No.'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of sale'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sold by'),
        ),
    ]
