# Generated by Django 4.2.6 on 2023-10-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_invoices_bill_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='imei_no',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='qty',
        ),
        migrations.CreateModel(
            name='InvoiceProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('imei_no', models.CharField(blank=True, help_text='Enter the unique IMEI No.', max_length=50, null=True, verbose_name='IMEI No.')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('invoice', models.ForeignKey(help_text='Select invoice', on_delete=django.db.models.deletion.CASCADE, to='product.invoices', verbose_name='Invoice')),
                ('product', models.ForeignKey(blank=True, help_text='Choose your desired product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Invoice Product',
                'verbose_name_plural': 'Invoice Products',
            },
        ),
    ]
