# Generated by Django 4.2.6 on 2023-10-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_invoices_imei_no_remove_invoices_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceProducts',
            new_name='InvoiceItems',
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
    ]
