# Generated by Django 4.2.6 on 2023-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_invoiceitems_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
