# Generated by Django 4.2.6 on 2023-10-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='Paid amount'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Invoice subtotal'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='taxable_amount',
            field=models.FloatField(default=0, verbose_name='Taxable amount'),
        ),
    ]
