# Generated by Django 4.2.6 on 2023-10-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_invoiceitems_cost_invoiceitems_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='description',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
    ]
