# Generated by Django 4.2.6 on 2023-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_invoiceitems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='description',
            field=models.CharField(blank=True, max_length=175, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='taxable_amount',
            field=models.FloatField(default=0, verbose_name='Total taxable amount'),
        ),
    ]
