# Generated by Django 4.2.6 on 2023-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_invoiceitems_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='taxable_amount',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='taxable_amount',
            field=models.FloatField(default=0, verbose_name='Taxable amount'),
        ),
    ]
