# Generated by Django 4.2.6 on 2023-10-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_invoices_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
