# Generated by Django 4.2.6 on 2023-10-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_invoiceitems_rate_alter_invoiceitems_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='description',
        ),
    ]
