# Generated by Django 4.2.6 on 2023-10-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_invoiceitems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
