# Generated by Django 4.2.6 on 2023-10-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='serial_no',
            field=models.CharField(blank=True, help_text='Enter the serial no.', max_length=50, null=True, verbose_name='Serial no.'),
        ),
    ]
