# Generated by Django 4.2.6 on 2023-10-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_serial_no_invoiceitems_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount(%)'),
        ),
    ]
