# Generated by Django 4.2.6 on 2023-10-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_finance'),
        ('product', '0016_invoices_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='customer_signature',
            field=models.BooleanField(default=False, verbose_name='Show Customer Signature box on invoice'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='ship_to_as_bill_to',
            field=models.BooleanField(default=True, verbose_name='Ship to same as bill to'),
        ),
        migrations.CreateModel(
            name='InvoiceShipToDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('post_office', models.CharField(blank=True, max_length=75, null=True, verbose_name='Post office')),
                ('district', models.CharField(blank=True, max_length=75, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=55, null=True, verbose_name='State')),
                ('pin_no', models.IntegerField(blank=True, null=True, verbose_name='PIN code number')),
                ('invoice', models.OneToOneField(help_text='Select invoice', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_ship_detail', to='product.invoices', verbose_name='Invoice')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.village', verbose_name='Select village')),
            ],
            options={
                'verbose_name': 'Ship to detail',
                'verbose_name_plural': 'Invoice Ship To Details',
            },
        ),
    ]
