# Generated by Django 4.2.6 on 2023-10-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_invoices_ship_to_as_bill_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='ship_to_as_bill_to',
            field=models.BooleanField(default=False, verbose_name='Ship to same as bill to'),
        ),
    ]
