# Generated by Django 4.2.6 on 2023-10-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_invoices_ship_to_as_bill_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceshiptodetail',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact No.'),
        ),
    ]
