# Generated by Django 4.2.6 on 2023-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_invoiceshiptodetail_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='paid_amount',
            field=models.IntegerField(default=0, verbose_name='Paid amount'),
        ),
    ]
