# Generated by Django 4.2.6 on 2023-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_invoices_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='advance_emi',
            field=models.IntegerField(default=0, verbose_name='Advance EMI'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='margin_money',
            field=models.IntegerField(default=0, verbose_name='Margin Money'),
        ),
    ]
