# Generated by Django 4.2.6 on 2024-01-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_invoices_invoice_total_invoices_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_total',
            field=models.FloatField(default=0, verbose_name='Invoice total'),
        ),
    ]
