# Generated by Django 4.2.6 on 2024-01-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_invoices_invoice_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='invoice_total',
        ),
    ]
