# Generated by Django 4.2.6 on 2025-06-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_invoiceconfiguration_pdf_scale'),
        ('product', '0026_remove_invoices_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.shopinformation'),
        ),
    ]
