# Generated by Django 4.2.6 on 2025-06-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_invoices_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='shop',
            new_name='store',
        ),
    ]
