# Use a slim Python base
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Expose the port
EXPOSE 8005

# Run app on container start
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8005"]
