services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: karan_enterprise_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: p2#)fg%Qst)5Y8b
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ayanng/karan-enterprise-app:v1.1
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8005"
    ports:
      - "8005:8005"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=karan_enterprise_db
      - DB_USER=admin
      - DB_PASSWORD=p2#)fg%Qst)5Y8b
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  mysql_data:
