# Generated by Django 4.2.6 on 2023-10-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_village'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoffice',
            name='dist',
        ),
        migrations.RemoveField(
            model_name='village',
            name='post_office',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='PostOffice',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
