# Generated by Django 4.2.6 on 2023-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_remove_postoffice_dist_remove_village_post_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUniqueIdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('id_length', models.IntegerField()),
                ('postfix', models.CharField(blank=True, max_length=5, null=True)),
                ('start_id', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'In active')], default=1)),
            ],
            options={
                'verbose_name': 'Unique ID configuration',
                'verbose_name_plural': 'Customer unique-id configurations',
            },
        ),
    ]
