# Generated by Django 4.2.6 on 2023-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Shop name')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Shop owner name')),
                ('mobile', models.CharField(max_length=10, verbose_name='Contact no.')),
                ('alternative_contact', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alternative contact no.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Shop email address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Shop website')),
                ('address', models.TextField(blank=True, help_text='Enter the address you want to appear on invoices.', null=True, verbose_name='Shop Address')),
            ],
            options={
                'verbose_name': 'Shop Information',
                'verbose_name_plural': 'Shop Information',
            },
        ),
        migrations.AlterField(
            model_name='customeruniqueidconfig',
            name='id_length',
            field=models.IntegerField(verbose_name='Length of Customer-Id'),
        ),
        migrations.AlterField(
            model_name='customeruniqueidconfig',
            name='postfix',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Postfix for Customer-Id'),
        ),
        migrations.AlterField(
            model_name='customeruniqueidconfig',
            name='prefix',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Prefix for Customer-Id'),
        ),
        migrations.AlterField(
            model_name='customeruniqueidconfig',
            name='start_id',
            field=models.IntegerField(default=0, verbose_name='Start indexing id'),
        ),
        migrations.AlterField(
            model_name='customeruniqueidconfig',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'In-active')], default=1),
        ),
    ]
