# Generated by Django 4.2.6 on 2023-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_shopinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinformation',
            name='logo_for_invoice',
            field=models.ImageField(blank=True, null=True, upload_to='shop-info/invoice-logo/'),
        ),
    ]
