# Generated by Django 4.2.6 on 2023-10-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_shopinformation_logo_for_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinformation',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GST No.'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle of shop'),
        ),
    ]
