# Generated by Django 4.2.6 on 2023-10-19 08:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_invoiceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'In-active')], default='active', max_length=15)),
                ('template', ckeditor.fields.RichTextField(verbose_name='Template Preview')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice PDF Templates',
            },
        ),
        migrations.DeleteModel(
            name='InvoiceConfig',
        ),
    ]
