# Generated by Django 4.2.6 on 2023-10-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_invoicepdftemplate_delete_invoiceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepdftemplate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'In-active')], default=1),
        ),
    ]
