# Generated by Django 4.2.6 on 2023-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_uniqueidconfig_delete_customeruniqueidconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'In-active')], default=1)),
                ('show_bank_detail', models.BooleanField(default=False, verbose_name='Show bank details on invoices')),
                ('show_tax_invoice', models.BooleanField(default=False, verbose_name='Show "Tax Invoice" on invoices')),
                ('show_quotation', models.BooleanField(default=False, verbose_name='Show "Quotation" on invoices')),
                ('digital_signature', models.BooleanField(default=False, verbose_name='Enable digital signatures on invoices')),
                ('show_finance_details', models.BooleanField(default=False, verbose_name='Show finance details on invoices')),
            ],
            options={
                'verbose_name': 'Invoice Configuration',
                'verbose_name_plural': 'Invoice Configurations',
            },
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='shop-info/digital-signature/'),
        ),
    ]
