# Generated by Django 4.2.6 on 2023-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_invoiceconfiguration_round_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinformation',
            name='ac_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='A/C Name'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='ac_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='A/C No.'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='branch',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='ifsc',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='IFSC No.'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='shop-info/payment-qr/', verbose_name='Payment QR'),
        ),
    ]
