# Generated by Django 4.2.6 on 2023-11-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_shopinformation_ac_name_shopinformation_ac_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='original_for_recipient',
            field=models.BooleanField(default=False, verbose_name='Show "ORIGINAL FOR RECIPIENT"'),
        ),
    ]
