# Generated by Django 4.2.6 on 2023-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_invoiceconfiguration_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceconfiguration',
            name='date_format',
            field=models.CharField(choices=[('format_1', 'Jun 08, 2004'), ('format_2', '08/06/2004'), ('format_3', '06/08/2004'), ('format_4', '2004/06/08'), ('format_5', '08-06-2004'), ('format_6', '06-08-2004'), ('format_7', '2004-06-08'), ('format_8', '08 Jun, 2004')], default='format_1', max_length=12),
        ),
    ]
