# Generated by Django 4.2.6 on 2023-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_alter_invoiceconfiguration_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact no.'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop name'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop owner name'),
        ),
    ]
