# Generated by Django 4.2.6 on 2023-11-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_alter_shopinformation_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceconfiguration',
            name='show_finance_details',
        ),
    ]
