# Generated by Django 4.2.6 on 2025-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_remove_invoiceconfiguration_show_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='pdf_scale',
            field=models.FloatField(default=0.7, help_text='PDF Scale only for playwright'),
        ),
    ]
