# Generated by Django 4.2.6 on 2023-10-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.')], max_length=10, null=True, verbose_name='Title')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name of the customer')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle name of the customer')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name of the customer')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address of the customer')),
                ('mobile', models.CharField(max_length=12, verbose_name='Mobile number of the customer')),
                ('unique_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer unique ID')),
                ('post_office', models.CharField(blank=True, max_length=75, null=True, verbose_name='Post office')),
                ('district', models.CharField(blank=True, max_length=75, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=55, null=True, verbose_name='State')),
                ('pin_no', models.IntegerField(blank=True, null=True, verbose_name='PIN code number')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Who added this customer?')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.village', verbose_name='Select village')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
