# Generated by Django 4.2.6 on 2023-10-26 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_alter_customer_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Who added this customer?', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
