# Generated by Django 4.2.6 on 2023-11-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
    ]
