# Generated by Django 4.2.6 on 2024-01-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Alternate mobile number of the customer'),
        ),
    ]
