# Generated by Django 4.2.6 on 2023-10-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('name', models.CharField(help_text='Ex. HDB Finance', max_length=100, verbose_name='Name of the finance.')),
                ('employee_name', models.CharField(help_text='Who will do the finance process. Ex. Sukhamay Chnada', max_length=255, verbose_name='Employee name')),
                ('employee_mobile', models.CharField(max_length=10, verbose_name='Employee mobile no.')),
            ],
            options={
                'verbose_name': 'Finance',
                'verbose_name_plural': 'Finances',
            },
        ),
    ]
