# Generated by Django 4.2.6 on 2023-11-07 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='finance_note',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Finance note for Invoice.'),
        ),
    ]
